import java.util.Random;
import java.util.Scanner;

public class Game {

    public static void startGame(){
        Scanner scanner = new Scanner(System.in);

        //start game
        System.out.println("Enter user selection (1-3");

        //create a variable to hold the user response using the Scanner object. The response needs to be an integer between 1-3 (1 = Rock, 2 = Paper, 3 = Scissors)
        int choice = scanner.nextInt();
        String user = "";
        if (choice == 1) {
            user = "rock";
        }
        else if (choice == 2) {
            user = "paper";
        }
        else if (choice == 3) {
            user = "scissors";
        }
        else {
            System.out.println("Answer not valid, I'll start over");
            startGame();
        }

        // create a variable to hold the cpu response generated by the getCPUResponse() method.
        String cpu = getCPUResponse();

        //compare user and cpu response with each other to decide the winner.
        if(user == cpu) {
            System.out.println("User chose " + user + ". " + "CPU chose " + cpu + ". " + "Game has ended in a draw!");
        }
        else if((user == "paper") && (cpu == "rock") ||
                (user == "rock") && (cpu == "scissors") ||
                (user == "scissors") && (cpu == "paper")) {
            System.out.println("User chose " + user + ". " + "CPU chose " + cpu + ". " + "User has won!");
        }
        else {
            System.out.println("User chose " + user + ". " + "CPU chose " + cpu + ". " + "CPU has won!");
        }
        System.out.println("Play again? 'y' to restart or any other key ends game.");
        String again = scanner.next();
        if (again.equals("y")) {
            startGame();
        }
        System.out.println("Nice Game!");
    }

    public static String getCPUResponse(){
        // Generate random integers in range 1 to 3
        Random r = new Random();
        int choice;
        String cpu;
        choice = 1 + r.nextInt(3);
        if (choice == 1) {
            cpu = "rock";
        }
        else if (choice == 2) {
            cpu = "paper";
        }
        else {
            cpu = "scissors";
        }
        return cpu;
    }

}
